### PR TITLE
Use empty search image as svg

### LINKED ISSUE #99: Bug: image not showing in `MegaMenuDropdown`
### Steps to reproduce the problem

- Visit the MegaMenuDropdown in the storybook
- type in the word `test` (or any string that won't exist in the results)

### What is the current behavior?

The image is not found

### What is the expected behavior?

There should be an image showing

### Screenshots

Screen Shot 2022-06-01 at 7 37 04 AM

(Same happens when implemented in Qiskit project)
Screen Shot 2022-06-01 at 7 35 37 AM

### Device

_No response_

### OS

_No response_

### Browser

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by abdonrd**
## Changes

Use empty search image as svg

Closes #99
Co-authored-by: @korgan00

Also change `svg` to `html` in icons

### CODE REVIEW

File: components/mega-menu-dropdown/index.ts [hunk 1]
```diff
@@ -115,14 +116,11 @@ export class QiskitMegaMenuDropdown extends LitElement {
...
   private emptyContentView() {
-    const imgSrc = new URL('../../assets/empty-search.png', import.meta.url)
-      .href;
-
     return html`
       <div class="content content-empty">
         <h2 class="content-empty__title">Nothing here</h2>
         <p class="content-empty__text">Try broadening your search terms</p>
-        <img alt="empty search" src="${imgSrc}" class="content-empty__image" />
+        ${emptySearchIcon}
```
Comment (techtolentino) [inline components/mega-menu-dropdown/index.ts:123]: 👏

**Review by techtolentino — APPROVED** [review]
Everything looks good to me @abdonrd 



Thank you too, @korgan00 



🚢
